/* AUTO-GENERATED by scripts/generate-srd-md-index.mjs — DO NOT EDIT BY HAND. */
import md0 from "./classes/barbarian.md";
import md1 from "./classes/bard.md";
import md2 from "./classes/cleric.md";
import md3 from "./classes/druid.md";
import md4 from "./classes/fighter.md";
import md5 from "./classes/monk.md";
import md6 from "./classes/paladin.md";
import md7 from "./classes/ranger.md";
import md8 from "./classes/rogue.md";
import md9 from "./classes/sorcerer.md";
import md10 from "./classes/warlock.md";
import md11 from "./classes/wizard.md";
import md12 from "./races/dragonborn.md";
import md13 from "./races/dwarf.md";
import md14 from "./races/elf.md";
import md15 from "./races/gnome.md";
import md16 from "./races/half-elf.md";
import md17 from "./races/half-orc.md";
import md18 from "./races/halfling.md";
import md19 from "./races/human.md";
import md20 from "./races/tiefling.md";
import md21 from "./subclasses/Circle of the Land.md";
import md22 from "./subclasses/College of Lore.md";
import md23 from "./subclasses/Draconic Bloodline.md";
import md24 from "./subclasses/Life Domain.md";
import md25 from "./subclasses/Oath of Devotion.md";
import md26 from "./subclasses/Path of the Berserker.md";
import md27 from "./subclasses/School of Evocation.md";
import md28 from "./subclasses/The Fiend.md";
import md29 from "./subclasses/Way of the Open Hand.md";
import md30 from "./subclasses/champion.md";
import md31 from "./subclasses/hunter.md";
import md32 from "./subclasses/thief.md";
import md33 from "./backgrounds/acolyte.md";
import md34 from "./feats/grappler.md";

export interface SrdMdEntry {
  type: string;
  slug: string;
  name: string;
  content: string;
}

export const SRD_MD_ENTRIES: SrdMdEntry[] = [
  { type: "classes", slug: "barbarian", name: "Barbarian", content: md0 },
  { type: "classes", slug: "bard", name: "Bard", content: md1 },
  { type: "classes", slug: "cleric", name: "Cleric", content: md2 },
  { type: "classes", slug: "druid", name: "Druid", content: md3 },
  { type: "classes", slug: "fighter", name: "Fighter", content: md4 },
  { type: "classes", slug: "monk", name: "Monk", content: md5 },
  { type: "classes", slug: "paladin", name: "Paladin", content: md6 },
  { type: "classes", slug: "ranger", name: "Ranger", content: md7 },
  { type: "classes", slug: "rogue", name: "Rogue", content: md8 },
  { type: "classes", slug: "sorcerer", name: "Sorcerer", content: md9 },
  { type: "classes", slug: "warlock", name: "Warlock", content: md10 },
  { type: "classes", slug: "wizard", name: "Wizard", content: md11 },
  { type: "races", slug: "dragonborn", name: "Dragonborn", content: md12 },
  { type: "races", slug: "dwarf", name: "Dwarf", content: md13 },
  { type: "races", slug: "elf", name: "Elf", content: md14 },
  { type: "races", slug: "gnome", name: "Gnome", content: md15 },
  { type: "races", slug: "half-elf", name: "Half-Elf", content: md16 },
  { type: "races", slug: "half-orc", name: "Half-Orc", content: md17 },
  { type: "races", slug: "halfling", name: "Halfling", content: md18 },
  { type: "races", slug: "human", name: "Human", content: md19 },
  { type: "races", slug: "tiefling", name: "Tiefling", content: md20 },
  { type: "subclasses", slug: "circle-of-the-land", name: "Circle of the Land", content: md21 },
  { type: "subclasses", slug: "college-of-lore", name: "College of Lore", content: md22 },
  { type: "subclasses", slug: "draconic-bloodline", name: "Draconic Bloodline", content: md23 },
  { type: "subclasses", slug: "life-domain", name: "Life Domain", content: md24 },
  { type: "subclasses", slug: "oath-of-devotion", name: "Oath of Devotion", content: md25 },
  { type: "subclasses", slug: "path-of-the-berserker", name: "Path of the Berserker", content: md26 },
  { type: "subclasses", slug: "school-of-evocation", name: "School of Evocation", content: md27 },
  { type: "subclasses", slug: "the-fiend", name: "The Fiend", content: md28 },
  { type: "subclasses", slug: "way-of-the-open-hand", name: "Way of the Open Hand", content: md29 },
  { type: "subclasses", slug: "champion", name: "Champion", content: md30 },
  { type: "subclasses", slug: "hunter", name: "Hunter", content: md31 },
  { type: "subclasses", slug: "thief", name: "Thief", content: md32 },
  { type: "backgrounds", slug: "acolyte", name: "Acolyte", content: md33 },
  { type: "feats", slug: "grappler", name: "Grappler", content: md34 },
];
